### ISSUE TITLE
Romantic Folklore Generator

### ISSUE THREAD

**Issue by videlais** [NaNoGenMo/2019#37]
I'm planning to play around with the act structures of romance stories and combine them with topics from folklore. The goal is to create code that could generate a few thousands words of a short story and build an anthology either based on the same initial seed theme or as grouped around the decided sexuality of the characters from the generation.

**Comment by replabjohn** [comment]
Sounds interesting. I tried doing something similar, but never got very far with it. You may find these articles useful for the folklore aspects:

Vladimir Propp's entry in Wikipedia:
https://en.wikipedia.org/wiki/Vladimir_Propp#Functions

Propp's Morphology of the Folk Tale
http://changingminds.org/disciplines/storytelling/plots/propp/propp.htm

Winter Mocha Random Story Generator: Proppâ?Ts Ratchet
http://www.gearheadrpg.com/2018/02/26/winter-mocha-random-story-generator-propps-ratchet/

**Comment by theairdemon** [comment]
Proppian folktales are super interesting if you decide to go that route. Regardless, looks like it'll be a really interesting project, good luck!
