### ISSUE TITLE
Time to shake the dust off

### ISSUE THREAD

**Issue by MichaelPaulukonis** [NaNoGenMo/2019#6]
I'm going to give something a shot.

I thought it was in November, so I've missed a couple of days....

**Comment by hugovk** [comment]
Yup, it's in November as usual, the doors are open on this repo for declaring intent :) 

> This activity starts at 12:01am GMT on Nov 1st and ends at 12:01am GMT Dec 1st.

**Comment by MichaelPaulukonis** [comment]
Oh,  thank goodness! Because it turns out most of my WordPress sites are hosed, because I've ignored then for 5 years. And trying to fix them (over is for my parents' business) I'm reminded why I hate PHP and WordPress so much.

**Comment by MichaelPaulukonis** [comment]
Yeah, I didn't do anything. Ugh.
