### ISSUE TITLE
Ordering a sandwich with...

### ISSUE THREAD

**Issue by lishap** [NaNoGenMo/2019#86]

**Comment by lishap** [comment]
[ingredients.txt](https://github.com/NaNoGenMo/2019/files/3843794/ingredients.txt)

**Comment by lishap** [comment]
https://github.com/dariusk/corpora/blob/master/data/foods/sandwiches.json

**Comment by lishap** [comment]
https://editor.p5js.org/lishap/sketches/OCJLEeMTR

**Comment by lishap** [comment]
[NanMoGenMo2019_Sandwich.txt](https://github.com/NaNoGenMo/2019/files/3902919/NanMoGenMo2019_Sandwich.txt)
This is the final code!

**Comment by hugovk** [comment]
I just ran it, this is fun! :)

Please could you also add an example novel created by the code?

**Comment by lishap** [comment]
Yes! Do you know how to export into a .txt file from the code specifically?
I was trying to use "sys.stdout = open('NaMoGenMo_novel.txt', 'wt')" put it
only exported an empty file.

**Comment by hugovk** [comment]
One way is to use the special `>` character on the command line. This redirects the output so instead of it printing to screen, send it into a file. For example:

```console
$ python my-python-script.py > NaNoGenMo_novel.txt
```

Could you try something like that?

**Comment by lishap** [comment]
[image: Screen Shot 2019-11-29 at 11.04.53 AM.png]

I'm getting this error! Maybe it's because it's on my desktop and not in a
specific place?

**Comment by hugovk** [comment]
The screenshot didn't get added when replying by email, please can you add it by dragging and dropping at the GitHub website?

**Comment by lishap** [comment]
<img width="774" alt="Screen Shot 2019-11-29 at 11 04 53 AM" src="https://user-images.githubusercontent.com/33298347/69886555-81d53880-12b0-11ea-91e5-592a459997ba.png">

**Comment by hugovk** [comment]
Try it with `python` at the start:

```sh
python NaMoGenMo_2019.py > NaNoGenMo_novel.txt
```

**Comment by lishap** [comment]
Awesome thank you @hugovk. Here is a .txt file of my novel! 
[NaNoGenMo_novel.txt](https://github.com/NaNoGenMo/2019/files/3907290/NaNoGenMo_novel.txt)

**Comment by lishap** [comment]
[NaMoGenMo19_SourceCode.txt](https://github.com/NaNoGenMo/2019/files/3907293/NaMoGenMo19_SourceCode.txt)

I changed the source code a little bit. Here's the updated code.

**Comment by hugovk** [comment]
Congratulations, have a "completed" label!

**Comment by lishap** [comment]
<img width="200" alt="Screen Shot 2019-11-30 at 5 08 13 PM" src="https://user-images.githubusercontent.com/33298347/69906606-0947a800-1394-11ea-8fb1-250039415d92.png">

**Comment by greg-kennedy** [comment]
@lishap hey, you might want to re-open this issue, we tend to leave issues open so people can find them with the default search!
